// <auto-generated />
namespace Painel_Projetos.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddTabelaTurma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTabelaTurma));
        
        string IMigrationMetadata.Id
        {
            get { return "202006130124022_AddTabelaTurma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
