// <auto-generated />
namespace Painel_Projetos.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AdicionadoCampo_TituloNaTabela_Projetos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionadoCampo_TituloNaTabela_Projetos));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240047305_AdicionadoCampo_TituloNaTabela_Projetos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
