// <auto-generated />
namespace Painel_Projetos.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class remove_Unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_Unique));
        
        string IMigrationMetadata.Id
        {
            get { return "202005160056532_remove_Unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
