// <auto-generated />
namespace Painel_Projetos.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Projetos_campoNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Projetos_campoNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240110185_Projetos_campoNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
